use crate::error::{Result, ShotgunError};
use crate::mapping::reader::MappingFormat;
use crate::mapping::types::MappingFile;

pub fn render_mapping_file(mapping: &MappingFile, format: MappingFormat) -> anyhow::Result<String> {
    Ok(match format {
        MappingFormat::Toml => render_toml(mapping)?,
        MappingFormat::Yaml => serde_yaml::to_string(mapping)?,
        MappingFormat::Json => serde_json::to_string_pretty(mapping)?,
    })
}

fn render_toml(mapping: &MappingFile) -> anyhow::Result<String> {
    let (mapped, total) = mapping.coverage();
    let pct = if total == 0 {
        0
    } else {
        (mapped * 100) / total
    };

    let mut header = String::new();
    header.push_str("# Auto-generated by Shotgun\n");
    header.push_str(&format!("# Source: {}\n", mapping.meta.source_spec));
    header.push_str(&format!("# Target: {}\n", mapping.meta.target_spec));
    header.push_str(&format!("# Generated: {}\n", mapping.meta.generated_at));
    header.push_str(&format!(
        "# Coverage: {mapped}/{total} endpoints mapped ({pct}%)\n\n"
    ));

    let body = toml::to_string_pretty(mapping)?;
    header.push_str(&body);
    Ok(header)
}

pub fn write_mapping_file(mapping: &MappingFile, path: &str, format: MappingFormat) -> Result<()> {
    let rendered = render_mapping_file(mapping, format).map_err(|e| ShotgunError::MappingWrite {
        path: path.to_string(),
        source: e,
    })?;
    std::fs::write(path, rendered).map_err(|e| ShotgunError::MappingWrite {
        path: path.to_string(),
        source: e.into(),
    })
}
